on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

name: lint and test
jobs:
  golangci:
    strategy:
      matrix:
        go-version:
          - "1.24"
          - "1.25"
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.4.0
      - name: test
        run: make test_ci
